name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: autoreconf
      run: autoreconf --force --install
    - name: configure
      run: ./configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
