name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install pkg-config libxcb libxcb-util libpam-dev libcairo-dev libfontconfig-dev libxcb-composite0 libxcb-composite0-dev libxcb-xinerama libxcb-randr libev libx11-xcb-dev libxkbcommon libxkbcommon-x11 libjpeg-turbo
    - name: autoreconf
      run: autoreconf --force --install
    - name: configure
      run: ./configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
